Verificando drivers

SQL Server
Microsoft Access Driver (*.mdb, *.accdb)
Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)
Microsoft Access Text Driver (*.txt, *.csv)
ODBC Driver 17 for SQL Server

Obtendo os dados do arquivo csv

Tratando os dados

In [ ]:
dados

         data       nome    id  vendas
0  2024-05-20    jackson  7839     4.0
1  2025-05-08     fatima  7840     5.0
2  2029-05-22   ivonildo  7841     9.0
3  2024-05-23     miguel  5842     2.0
4  2024-05-24     junior  7843     7.0
5  2024-05-25      alana  5124     3.0
6  2024-05-26        leo  5851     8.0
7  2024-05-27      pedro  7846    10.0
8         NaT  valquiria  6248     NaN
9  2024-05-29        NaN  6249     2.0
10 2023-05-30        NaN  7849     1.0
11 2024-05-31        NaN  7850     1.0
12 2024-06-01        NaN  7851     1.0
13 2022-06-02        NaN  7852     1.0
14 2024-06-03        NaN  7853     1.0

         data       nome    id  vendas
0  2024-05-20    jackson  7839     4.0
1  2025-05-08     fatima  7840     5.0
2  2029-05-22   ivonildo  7841     9.0
3  2024-05-23     miguel  5842     2.0
4  2024-05-24     junior  7843     7.0
5  2024-05-25      alana  5124     3.0
6  2024-05-26        leo  5851     8.0
7  2024-05-27      pedro  7846    10.0
8         NaT  valquiria  6248     0.0
9  2024-05-29        NaN  6249     2.0
10 2023-05-30        NaN  7849     1.0
11 2024-05-31        NaN  7850     1.0
12 2024-06-01        NaN  7851     1.0
13 2022-06-02        NaN  7852     1.0
14 2024-06-03        NaN  7853     1.0

In [ ]:
dados['vendas'] = dados['vendas'].astype(int)
display(dados)

         data       nome    id  vendas
0  2024-05-20    jackson  7839       4
1  2025-05-08     fatima  7840       5
2  2029-05-22   ivonildo  7841       9
3  2024-05-23     miguel  5842       2
4  2024-05-24     junior  7843       7
5  2024-05-25      alana  5124       3
6  2024-05-26        leo  5851       8
7  2024-05-27      pedro  7846      10
8         NaT  valquiria  6248       0
9  2024-05-29        NaN  6249       2
10 2023-05-30        NaN  7849       1
11 2024-05-31        NaN  7850       1
12 2024-06-01        NaN  7851       1
13 2022-06-02        NaN  7852       1
14 2024-06-03        NaN  7853       1

Subindo os dados no banco

15

In [ ]:
dados

         data       nome    id  vendas
0  2024-05-20    jackson  7839       4
1  2025-05-08     fatima  7840       5
2  2029-05-22   ivonildo  7841       9
3  2024-05-23     miguel  5842       2
4  2024-05-24     junior  7843       7
5  2024-05-25      alana  5124       3
6  2024-05-26        leo  5851       8
7  2024-05-27      pedro  7846      10
8         NaT  valquiria  6248       0
9  2024-05-29        NaN  6249       2
10 2023-05-30        NaN  7849       1
11 2024-05-31        NaN  7850       1
12 2024-06-01        NaN  7851       1
13 2022-06-02        NaN  7852       1
14 2024-06-03        NaN  7853       1